/**
 * AUTO-GENERATED by scripts/generate-avatar-gallery.mjs
 * Do not edit by hand. The prebuild script overwrites this file on every build
 * with whatever image files currently exist in public/avatars/gallery/.
 *
 * Supports any number of files and any names (.jpg / .png / .webp / .gif).
 */
export const AVATAR_GALLERY = [
  // Will be replaced at build time by the generator with real files present in the folder.
] as const;

export type AvatarId = (typeof AVATAR_GALLERY)[number];

/** Returns the public URL for an avatar file (includes extension). */
export function avatarUrl(filename: string): string {
  return `/avatars/gallery/${filename}`;
}
