export const DIRECTORY_SLICE = [
  {
    id: "dir-weekly-cadence",
    title: "Weekly X cadence, owner still hits publish",
    bot: "SparkBot",
    owner: "botdirectory.ai",
    type: "Directory Prompt",
    price: "Free · attributed",
    desc: "Cadence and draft suggestions for an X desk. Human still publishes. Source: Account Growth Coach on botdirectory.ai.",
    tags: ["reach", "x", "cadence"],
    vibe: "energetic",
    installs: 354,
    href: "https://botdirectory.ai/bots/account-growth-coach/",
  },
  {
    id: "dir-inbox-sweep",
    title: "Inbox sweep with a human send gate",
    bot: "HelperBot 2.0",
    owner: "botdirectory.ai",
    type: "Directory Prompt",
    price: "Free · attributed",
    desc: "Triage and draft replies. Nothing leaves the inbox until a human taps send. Source: Inbox Marie Kondo.",
    tags: ["desk", "email", "gate"],
    vibe: "efficient",
    installs: 35,
    href: "https://botdirectory.ai/bots/inbox-marie-kondo/",
  },
  {
    id: "dir-repo-watch",
    title: "Repo event watch, review before merge",
    bot: "NightGuardian",
    owner: "botdirectory.ai",
    type: "Directory Prompt",
    price: "Free · attributed",
    desc: "Watch issues and PRs, draft a review, wait for the human. Source: GitHub Issue and PR Triage.",
    tags: ["forge", "github", "review"],
    vibe: "vigilant",
    installs: 0,
    href: "https://botdirectory.ai/bots/github-issue-and-pr-triage/",
  },
  {
    id: "dir-crew-router",
    title: "Route work across a short bot crew",
    bot: "CoalitionRunner",
    owner: "botdirectory.ai",
    type: "Directory Prompt",
    price: "Free · attributed",
    desc: "One front desk that hands work to specialists. Quiet hours and a human gate on irreversible steps. Source: Chief of Staff Router.",
    tags: ["crew", "router", "approval"],
    vibe: "focused",
    installs: 0,
    href: "https://botdirectory.ai/bots/chief-of-staff-router/",
  },
  {
    id: "dir-challenge-plan",
    title: "Challenge the plan before it ships",
    bot: "VibeGuardian",
    owner: "botdirectory.ai",
    type: "Directory Prompt",
    price: "Free · attributed",
    desc: "Adversarial pass on a draft plan. Flags weak claims. Does not ship anything. Source: Adversarial Reviewer.",
    tags: ["spark", "review", "safety"],
    vibe: "protect",
    installs: 0,
    href: "https://botdirectory.ai/bots/adversarial-reviewer/",
  },
  {
    id: "dir-cupboard-meals",
    title: "Meal plan from what is already in the house",
    bot: "LunaBot",
    owner: "botdirectory.ai",
    type: "Directory Prompt",
    price: "Free · attributed",
    desc: "Cook from the cupboard, not a shopping list fantasy. Source: Cupboard Meal Planner.",
    tags: ["garden", "meals", "home"],
    vibe: "warm",
    installs: 0,
    href: "https://botdirectory.ai/bots/cupboard-meal-planner/",
  },
  {
    id: "dir-multi-desk",
    title: "Drafts for several X desks, none auto-post",
    bot: "SparkBot",
    owner: "botdirectory.ai",
    type: "Directory Prompt",
    price: "Free · attributed",
    desc: "Separate draft piles per desk. Owner still hits publish on each. Source: Multi-Account Content Desk.",
    tags: ["signal", "x", "drafts"],
    vibe: "energetic",
    installs: 0,
    href: "https://botdirectory.ai/bots/multi-account-content-desk/",
  },
  {
    id: "dir-disk-sweep",
    title: "Weekly disk sweep, list first",
    bot: "HelperBot 2.0",
    owner: "botdirectory.ai",
    type: "Directory Prompt",
    price: "Free · attributed",
    desc: "Find stale files and propose a tidy list. Delete only after the human agrees. Source: Weekly Disk Cleanup.",
    tags: ["desk", "cleanup", "gate"],
    vibe: "efficient",
    installs: 0,
    href: "https://botdirectory.ai/bots/weekly-disk-cleanup/",
  },
  {
    id: "dir-chrome-sketch",
    title: "Chrome extension sketch, review before ship",
    bot: "SparkBot",
    owner: "botdirectory.ai",
    type: "Directory Prompt",
    price: "Free · attributed",
    desc: "Scaffold an extension idea. Human reviews code before it leaves the machine. Source: Chrome Extension Builder.",
    tags: ["forge", "chrome", "scaffold"],
    vibe: "builder",
    installs: 0,
    href: "https://botdirectory.ai/bots/chrome-extension-builder/",
  },
  {
    id: "dir-bot-tune",
    title: "Tune a bot prompt without rewriting its soul",
    bot: "DeepDive",
    owner: "botdirectory.ai",
    type: "Directory Prompt",
    price: "Free · attributed",
    desc: "Tighten instructions and gates. Keep the original voice. Source: Bot Optimizer.",
    tags: ["spark", "prompt", "tune"],
    vibe: "deep",
    installs: 0,
    href: "https://botdirectory.ai/bots/bot-optimizer/",
  },
];
