CREATE TABLE IF NOT EXISTS schema_migrations (version integer PRIMARY KEY, applied_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE owners (id text PRIMARY KEY, github_id text UNIQUE, handle text NOT NULL, display_name text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE sessions (id_hash text PRIMARY KEY, owner_id text NOT NULL REFERENCES owners(id), csrf_token text NOT NULL, expires_at timestamptz NOT NULL);
CREATE TABLE oauth_states (state_hash text PRIMARY KEY, expires_at timestamptz NOT NULL);
CREATE TABLE circles (id text PRIMARY KEY, owner_id text NOT NULL UNIQUE REFERENCES owners(id), name text NOT NULL);
CREATE TABLE circle_members (circle_id text NOT NULL REFERENCES circles(id), owner_id text NOT NULL REFERENCES owners(id), role text NOT NULL CHECK(role IN ('owner','member')), active boolean NOT NULL DEFAULT true, PRIMARY KEY(circle_id,owner_id));
CREATE TABLE circle_invites (code_hash text PRIMARY KEY, circle_id text NOT NULL REFERENCES circles(id), expires_at timestamptz NOT NULL, consumed_at timestamptz);
CREATE TABLE bots (id text PRIMARY KEY, owner_id text NOT NULL REFERENCES owners(id), name text NOT NULL, role text NOT NULL CHECK(role IN ('scout','delegate')), runtime text NOT NULL CHECK(runtime IN ('native-grok','grok-compatible')), status text NOT NULL CHECK(status IN ('active','paused','revoked')), token_hash text NOT NULL UNIQUE, last_seen_at timestamptz, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE pairings (code_hash text PRIMARY KEY, owner_id text NOT NULL REFERENCES owners(id), expires_at timestamptz NOT NULL, consumed_at timestamptz);
CREATE TABLE missions (id text PRIMARY KEY, owner_id text NOT NULL REFERENCES owners(id), title text NOT NULL, brief text NOT NULL, status text NOT NULL CHECK(status IN ('queued','running','completed','failed')), visibility text NOT NULL CHECK(visibility IN ('private','circle')), circle_id text REFERENCES circles(id), max_rounds integer NOT NULL CHECK(max_rounds BETWEEN 1 AND 5), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE tasks (id text PRIMARY KEY, mission_id text NOT NULL REFERENCES missions(id), bot_id text NOT NULL REFERENCES bots(id), round integer NOT NULL, status text NOT NULL CHECK(status IN ('queued','leased','completed','failed')), attempts integer NOT NULL DEFAULT 0, attempt_id text, lease_expires_at timestamptz, idempotency_key text, result_hash text, evidence_id text, UNIQUE(mission_id,bot_id,round));
CREATE TABLE evidence (id text PRIMARY KEY, owner_id text NOT NULL REFERENCES owners(id), mission_id text REFERENCES missions(id), bot_id text REFERENCES bots(id), title text NOT NULL, summary text NOT NULL, source_url text, sources jsonb NOT NULL DEFAULT '[]', visibility text NOT NULL CHECK(visibility IN ('private','circle')), circle_id text REFERENCES circles(id), created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE approvals (id text PRIMARY KEY, owner_id text NOT NULL REFERENCES owners(id), evidence_id text NOT NULL REFERENCES evidence(id), circle_id text NOT NULL REFERENCES circles(id), status text NOT NULL CHECK(status IN ('pending','approved','rejected')), version integer NOT NULL DEFAULT 1, evidence_hash text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE events (id text PRIMARY KEY, owner_id text NOT NULL REFERENCES owners(id), type text NOT NULL, message text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX bots_owner ON bots(owner_id);
CREATE INDEX missions_owner ON missions(owner_id);
CREATE INDEX tasks_claim ON tasks(bot_id,status,round);
CREATE INDEX evidence_owner ON evidence(owner_id);
CREATE INDEX evidence_circle ON evidence(circle_id,visibility);
CREATE INDEX approvals_owner ON approvals(owner_id);
CREATE INDEX events_owner_time ON events(owner_id,created_at);
